spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot1102
    username: root
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
